-- adding values to todo table, which is automatically generated by entity
insert into TODO(ID,USER_NAME,DESCRIPTION,TARGET_DATE, CUSTOM_TEST_COULUMN_NAME,DONE) 
values(1001, 'tester', 'testDescription1',CURRENT_DATE,'',false);

insert into TODO(ID,USER_NAME,DESCRIPTION,TARGET_DATE, CUSTOM_TEST_COULUMN_NAME,DONE) 
values(1002, 'admin', 'adminDescription1',CURRENT_DATE,'',false);

insert into TODO(ID,USER_NAME,DESCRIPTION,TARGET_DATE, CUSTOM_TEST_COULUMN_NAME,DONE) 
values(1003, 'tester', 'testDescription2',CURRENT_DATE,'',false);

insert into TODO(ID,USER_NAME,DESCRIPTION,TARGET_DATE, CUSTOM_TEST_COULUMN_NAME,DONE) 
values(1004, 'tester', 'testDescription3',CURRENT_DATE,'',false);

insert into TODO(ID,USER_NAME,DESCRIPTION,TARGET_DATE, CUSTOM_TEST_COULUMN_NAME,DONE) 
values(1005, 'admin', 'adminDescription2',CURRENT_DATE,'',false);